name: Test Docker Login
on:
  push:
    paths:
      - '.github/**'
  workflow_dispatch:

jobs:
  docker-login-test:
    runs-on: self-hosted
    steps:
      - name: Test DockerHub Login
        shell: powershell
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSCODE: ${{ secrets.DOCKER_PASSCODE }}
        run: |
          docker logout | Out-Null
          echo $env:DOCKER_PASSCODE | docker login -u $env:DOCKER_USERNAME --password-stdin
          docker info
